### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by loicNorgeot** [loicNorgeot/mesh-addon#2]
- [x] Fixer le problème de l'ouverture des fichiers en mode binaire
- [x] Fixer le problème de vtk: ne faire l'import que si on clique dessus
- [ ] Permettre de choisir la valeur des isosurfaces dans vtk
- [ ] Donner plus d'exemples d'utilisation
